#!/bin/bash

last_modified_timestamps=""
watched_extensions=".c .h"

while true; do
    current_modified_timestamps=$(find . -not -path "./build*" -type f \( -name "*.c" -o -name "*.h" \) -printf '%T@ %p\n' | sort)
    current_time=$(date "+%Y-%m-%d %H:%M:%S")

    if [ "$current_modified_timestamps" != "$last_modified_timestamps" ]; then
         clear
        echo "Changes detected at: $current_time, recompiling..."
          ./compile && ./tests $1
        last_modified_timestamps="$current_modified_timestamps"
    fi

    sleep 1
done
